import {describe,it,expect,vi} from "vitest";
import {mkdtemp,writeFile,readFile,stat} from "node:fs/promises";
import {tmpdir} from "node:os";import{join}from"node:path";
import{connect}from"@thenavidm/slipway/testing";
import{loadConfig}from"../src/config.js";import{BeehiivClient}from"../src/api/client.js";
import{createApp}from"../src/app.js";import{ALL_TOOLS,compileAll}from"../src/tools/index.js";
const PUB="pub_00000000-0000-0000-0000-000000000000";const POST="post_00000000-0000-0000-0000-000000000000";
const key="private-fixture-key-not-a-real-credential";
function json(body:unknown,status=200,headers:Record<string,string>={}){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json",...headers}});}
// The real Slipway server with an injected client, so the network stays a stub. A call to a hidden tool is a
// protocol error rather than a tool result; both are refusals a client sees.
async function harness(fetcher:typeof fetch,env:NodeJS.ProcessEnv={}){
 const settings={BEEHIIV_API_KEY:key,BEEHIIV_MIN_REQUEST_INTERVAL_MS:"1",...env};const config=loadConfig(settings);const api=new BeehiivClient(config,fetcher,async()=>{});
 const mcp=await connect(createApp({context:()=>({config,client:api})}),{env:settings});
 return {client:{listTools:async()=>({tools:await mcp.listTools()})},api,close:()=>mcp.close(),call:async(name:string,args:Record<string,unknown>={})=>{try{const r=await mcp.callTool(name,args);return{error:r.isError===true,value:JSON.parse((r.content as{type:string;text:string}[])[0].text)};}catch(e){return{error:true,value:{error:(e as Error).message}};}}};
}
describe("current Beehiiv request and safety behavior",()=>{
 it("compiles every input and body schema with the native validator",()=>expect(compileAll()).toBe(ALL_TOOLS.length));
 it("discovers 117 tools and 70 reads without account auth",async()=>{const f=vi.fn();const h=await harness(f,{BEEHIIV_API_KEY:""});try{const t=(await h.client.listTools()).tools;expect(t).toHaveLength(117);expect(t.filter(t=>t.annotations?.readOnlyHint)).toHaveLength(70);expect(t.filter(t=>t.annotations?.destructiveHint)).toHaveLength(47);expect(f).not.toHaveBeenCalled();}finally{await h.close();}});
 it("read-only hides writes and refuses a direct hidden call",async()=>{const f=vi.fn();const h=await harness(f,{BEEHIIV_READ_ONLY:"1"});try{expect((await h.client.listTools()).tools).toHaveLength(70);expect((await h.call("create_post",{publication_id:PUB,title:"Draft",body_content:"<p>Draft</p>",confirm:true})).error).toBe(true);expect(f).not.toHaveBeenCalled();}finally{await h.close();}});
 it("confirmation and destructive policy gate every write before HTTP",async()=>{for(const env of[{}, {BEEHIIV_ALLOW_DESTRUCTIVE:"0"}]){const f=vi.fn();const h=await harness(f,env);try{expect((await h.call("create_post",{publication_id:PUB,title:"Draft",body_content:"<p>Draft</p>",confirm:env.BEEHIIV_ALLOW_DESTRUCTIVE?true:false})).error).toBe(true);expect(f).not.toHaveBeenCalled();}finally{await h.close();}}});
 it("uses Bearer API auth and only the fixed v2 origin",async()=>{const f=vi.fn(async(u:unknown,i:RequestInit)=>{expect(String(u)).toBe("https://api.beehiiv.com/v2/publications");expect((i.headers as Record<string,string>).Authorization).toBe(`Bearer ${key}`);expect(i.redirect).toBe("error");return json({data:[]});})as typeof fetch;const h=await harness(f);try{expect((await h.call("list_publications")).error).toBe(false);}finally{await h.close();}});
 it("creates an unscheduled draft and reports asynchronous acceptance",async()=>{const f=vi.fn(async(_u:unknown,i:RequestInit)=>{const b=JSON.parse(i.body as string);expect(b.status).toBe("draft");expect(b.scheduled_at).toBeUndefined();return json({data:{id:POST}},201);})as typeof fetch;const h=await harness(f);try{const r=await h.call("create_post",{publication_id:PUB,title:"Draft",body_content:"<p>Draft</p>",confirm:true});expect(r.error).toBe(false);expect(r.value.creation_pending).toBe(true);expect(r.value.data.id).toBe(POST);}finally{await h.close();}});
 it("rejects missing/both content methods and scheduling a draft",async()=>{const f=vi.fn();const h=await harness(f);try{for(const x of[{}, {blocks:[{type:"paragraph",plaintext:"Draft"}],body_content:"<p>Draft</p>"},{body_content:"<p>Draft</p>",scheduled_at:"2026-10-10T12:00:00Z"}]){expect((await h.call("create_post",{publication_id:PUB,title:"Draft",confirm:true,...x})).error).toBe(true);}expect(f).not.toHaveBeenCalled();}finally{await h.close();}});
 it("validates current structured blocks and preserves nullable inherited headers",async()=>{const f=vi.fn(async(_u:unknown,i:RequestInit)=>{const b=JSON.parse(i.body as string);expect(b.blocks[0].type).toBe("paragraph");expect(b.headers["X-Example"]).toBeNull();return json({data:{id:POST}},201);})as typeof fetch;const h=await harness(f);try{expect((await h.call("create_post",{publication_id:PUB,confirm:true,payload:{title:"Draft",blocks:[{type:"paragraph",plaintext:"Draft"}],headers:{"X-Example":null}}})).error).toBe(false);}finally{await h.close();}});
 it("exposes HTTP 202 as pending and honors no automatic create retry",async()=>{const f=vi.fn(async()=>json({data:null},202,{"Retry-After":"3"}))as typeof fetch;const h=await harness(f);try{const r=await h.call("get_post",{publication_id:PUB,post_id:POST});expect(r.error).toBe(false);expect(r.value.http_status).toBe(202);expect(r.value.creation_pending).toBe(true);expect(r.value.retry_after).toBe("3");expect(f).toHaveBeenCalledTimes(1);}finally{await h.close();}});
 it("reports post creation failure rather than retrying or recreating",async()=>{const f=vi.fn(async()=>json({error:"POST_CREATION_FAILED"},404))as typeof fetch;const h=await harness(f);try{const r=await h.call("get_post",{publication_id:PUB,post_id:POST});expect(r.error).toBe(true);expect(JSON.stringify(r.value)).toContain("POST_CREATION_FAILED");expect(f).toHaveBeenCalledTimes(1);}finally{await h.close();}});
 it("aggregates actual cursor pages without skipping a capped remainder",async()=>{const calls:string[]=[];const f=vi.fn(async(u:unknown)=>{const url=new URL(String(u));calls.push(String(u));const limit=Number(url.searchParams.get("limit"));const second=url.searchParams.get("cursor")==="next";expect(limit).toBe(second?1:2);return json({data:second?[{id:3}]:[{id:1},{id:2}],pagination:{has_more:true,next_cursor:second?"last":"next"}});})as typeof fetch;const h=await harness(f);try{const r=await h.call("list_subscriptions",{publication_id:PUB,limit:2,all_pages:true,max_items:3});expect(r.error).toBe(false);expect(r.value.collected).toBe(3);expect(r.value.truncated).toBe(true);expect(r.value.pagination.next_cursor).toBe("last");expect(calls).toHaveLength(2);}finally{await h.close();}});
 it("rejects cursor/page mixtures and repeated cursors",async()=>{const f=vi.fn(async()=>json({data:[{id:1}],pagination:{has_more:true,next_cursor:"same"}}))as typeof fetch;const h=await harness(f);try{expect((await h.call("list_subscriptions",{publication_id:PUB,cursor:"x",page:2})).error).toBe(true);expect(f).not.toHaveBeenCalled();expect((await h.call("list_subscriptions",{publication_id:PUB,limit:1,all_pages:true,max_items:5})).error).toBe(true);expect(f).toHaveBeenCalledTimes(2);}finally{await h.close();}});
 it("does not advertise aggregation on offset-only operations",()=>{for(const t of ALL_TOOLS){const p=t.inputSchema.properties;if(p.all_pages)expect(p.cursor).toBeDefined();}});
 it("refuses empty partial updates and mixed payload/body inputs before HTTP",async()=>{const f=vi.fn();const h=await harness(f);try{expect((await h.call("update_post",{publication_id:PUB,post_id:POST,confirm:true})).error).toBe(true);expect((await h.call("update_post",{publication_id:PUB,post_id:POST,title:"One",payload:{title:"Two"},confirm:true})).error).toBe(true);expect(f).not.toHaveBeenCalled();}finally{await h.close();}});
 it("reads a regular private payload file and validates it before a request",async()=>{const dir=await mkdtemp(join(tmpdir(),"beehiiv-test-"));const file=join(dir,"draft.json");await writeFile(file,JSON.stringify({title:"Draft",body_content:"<p>Draft</p>"}),{mode:0o600});const f=vi.fn(async()=>json({data:{id:POST}},201))as typeof fetch;const h=await harness(f);try{expect((await h.call("create_post",{publication_id:PUB,payload_file:file,confirm:true})).error).toBe(false);await writeFile(file,"{invalid");expect((await h.call("create_post",{publication_id:PUB,payload_file:file,confirm:true})).error).toBe(true);expect(f).toHaveBeenCalledTimes(1);}finally{await h.close();}});
 it("never automatically retries a mutating 429 or network timeout",async()=>{for(const f of[vi.fn(async()=>json({error:"limit"},429)),vi.fn(async()=>{throw new Error("network");})]){const h=await harness(f as typeof fetch);try{expect((await h.call("create_post",{publication_id:PUB,title:"Draft",body_content:"<p>Draft</p>",confirm:true})).error).toBe(true);expect(f).toHaveBeenCalledTimes(1);}finally{await h.close();}}});
 it("bounded GET rate retry preserves request identity and private auth",async()=>{const f=vi.fn().mockResolvedValueOnce(json({error:"limit"},429,{"Retry-After":"1"})).mockResolvedValueOnce(json({data:[]}));const h=await harness(f);try{expect((await h.call("list_publications")).error).toBe(false);expect(f).toHaveBeenCalledTimes(2);expect(String(f.mock.calls[0][0])).toBe(String(f.mock.calls[1][0]));}finally{await h.close();}});
 it("refreshes public OAuth with form encoding and atomically private persistence",async()=>{const dir=await mkdtemp(join(tmpdir(),"beehiiv-oauth-"));const file=join(dir,"oauth.json");await writeFile(file,JSON.stringify({access_token:"expired-fixture",refresh_token:"refresh-fixture",client_id:"public-fixture",created_at:1,expires_in:1}),{mode:0o600});const f=vi.fn(async(u:unknown,i:RequestInit)=>{if(String(u)==="https://app.beehiiv.com/oauth/token"){expect((i.headers as Record<string,string>)["Content-Type"]).toBe("application/x-www-form-urlencoded");const b=new URLSearchParams(i.body as string);expect(b.get("grant_type")).toBe("refresh_token");expect(b.get("client_secret")).toBeNull();return json({access_token:"renewed-fixture",refresh_token:"next-fixture",expires_in:3600});}expect((i.headers as Record<string,string>).Authorization).toBe("Bearer renewed-fixture");return json({data:[]});})as typeof fetch;const h=await harness(f,{BEEHIIV_API_KEY:"",BEEHIIV_TOKENS_FILE:file});try{expect((await h.call("list_publications")).error).toBe(false);const saved=JSON.parse(await readFile(file,"utf8"));expect(saved.access_token).toBe("renewed-fixture");if(process.platform!=="win32")expect((await stat(file)).mode&0o777).toBe(0o600);}finally{await h.close();}});
 it("refuses API-key-only OAuth user identity before HTTP",async()=>{const f=vi.fn();const h=await harness(f);try{const r=await h.call("identify_oauth_user");expect(r.error).toBe(true);expect(f).not.toHaveBeenCalled();}finally{await h.close();}});
 it("keeps reflected credentials and local account secret paths out of output",async()=>{const f=vi.fn(async()=>json({error:`bad ${key}`},401))as typeof fetch;const h=await harness(f);try{const r=await h.call("list_publications");expect(JSON.stringify(r.value)).not.toContain(key);expect(JSON.stringify((await h.call("list_accounts")).value)).not.toContain(key);}finally{await h.close();}});
 it("encodes email path values without permitting a foreign API origin",async()=>{const f=vi.fn(async(u:unknown)=>{const v=new URL(String(u));expect(v.origin).toBe("https://api.beehiiv.com");expect(v.pathname).toContain("a%2Bb%40example.com");return json({data:{}});})as typeof fetch;const h=await harness(f);try{expect((await h.call("get_subscription_by_email",{publication_id:PUB,email:"a+b@example.com"})).error).toBe(false);await expect(h.api.request("GET","https://attacker.example/v2/publications")).rejects.toThrow(/Unsupported/);}finally{await h.close();}});
});
